<!DOCTYPE html>
<html>
<body>

<div align="center">
<h3>Prepared by Shaig E.Kazimov</h3>
    
<h1>Python exercises</h1>

<h3>Follow Me on - <a href="https://www.linkedin.com/in/shaig-kazimov/">LinkedIn</a>&nbsp;

</div>
</body>
</html>

# Variables

Create a variable with name "x" and a value of 10. Execute.

In [2]:
x = 10

Tell the computer to show you the value of that variable.

In [3]:
# Executing variable
x

10

Can you think of a second way to obtain the same result?

In [4]:
# Printing the variable
print(x)

10


On the same line, create four new variables: a,b,c, and d, that are equal to 10, 20, 30, and 40, respectively.

In [9]:
a, b, c, d = 10, 20, 30, 40
print(f"a: {a}\nb: {b}\nc: {c}\nd: {d}")

a: 10
b: 20
c: 30
d: 40


Tell the computer to show you the value corresponding to the variable "b".

In [6]:
b

20

Do the same for "d".

In [7]:
d

40

_________________________________

# Numbers and Boolean Values

Create a variable equal to "True".

In [12]:
bool_variable = True

Check its type.

In [13]:
# Method 1
type(bool_variable)

bool

In [14]:
# Method 2
isinstance(bool_variable, bool)

True

Create a variable equal to 99.

In [16]:
number = 99

Check its type.

In [17]:
# Method 1
type(number)

int

In [18]:
# Method 2
isinstance(number, int)

True

Check the type of the value 0.99.

In [19]:
type(0.99)

float

Turn 99 into a float.

In [21]:
float(99)

99.0

Turn 0.99 into an integer. What value did you get?

In [26]:
#  For floating-point numbers, this truncates towards zero. (This info come from help(int))
int(0.99)

0

_________________________________

# Strings

Assign the value of 100 to the variable "m".

In [28]:
m = 100

With the help of the variable "m", write one line of code where the output after executuion would be 100 days.

Hint: You could provide four answers to this question!

In [40]:
# 1. f-string method (best way)
f"{m} days"

'100 days'

In [41]:
# 2. concationation method (After type casting from int to str)
str(m) + " days"

'100 days'

In [42]:
# 3. %-string formatting
"%s days" % (m)

'100 days'

In [43]:
# 4. string.format(*args) method
"{} days".format(m)

'100 days'

In [44]:
# 5. string.format(**kwargs) method
"{day} days".format(day = m)

'100 days'

In [46]:
# 6. print() method
print(m, "days")

100 days


Produce an output equal to It's cool, isn't it?

In [47]:
"It's cool, isn't it?"

It's cool, isn't it?


Fix the string below.

In [48]:
"Don't be shy"

"Don't be shy"

Produce an output equal to Click "OK".

In [54]:
print("Click \"OK\"")

Click "OK"


Include a plus sign in your line of code to produce 'Big Houses'.

In [50]:
"Big" + " Houses"

'Big Houses'

Include a trailing comma in your line of code to produce Big Houses.

In [52]:
print("Big", "Houses")

Big Houses


__________________

# Arithmetic operators

Combine 15 and 23.

In [55]:
"15" + "23"

'1523'

Subtract 50 from 26.

In [56]:
26 - 50

-24

Divide 20 by 4.

In [57]:
20 / 4

5.0

Divide 22 by 4.

In [58]:
22 / 4

5.5

Obtain the remainder of the division of 22 by 4.

In [59]:
22 % 4

2

Divide the float 22 by 4.

In [60]:
22.0 / 4

5.5

In [61]:
float(22) / 4

5.5

Multiply 6 by 8.

In [62]:
6 * 8

48

Raise 15 to the power of 2.

In [63]:
15 ** 2

225

_____________________

# The double-equality sign

Demonstrate that 100 is not equal to 98.

In [64]:
100 == 98

False

__________________________

# Reassign Values

Assign the value of 14 to a variable p.

In [65]:
p = 14

Calculate p + 10.

In [66]:
p + 10

24

Now, assign 30 to the variable p.

In [67]:
p = 30

Calculate p + 10.

In [68]:
p + 10

40

Observe how the value of p is always the last one you have assigned.

In [74]:
# The variables and values is not directly connnected.
# When we create variable and assign some value to the variable
# in the background variable preserve the pointer which points the actual value in memory
p = 14
print("Id of p:", id(p))
p + 10
print("Id of p:", id(p))
# The id of the p variable the same but in the memory which value is pointing we perform calculation on top of it
print("---After reassign---")
p = 30
print("Id of p:", id(p))
p + 10
print("Id of p:", id(p))
# When we reassign new value to the p varaible in the memory the position is changed and the id is changed accordingly

Id of p: 140731751441736
Id of p: 140731751441736
---After reassign---
Id of p: 140731751442248
Id of p: 140731751442248


___________________

# Indexing Elements

Extract the letter 'B' from "Bingo!".

In [78]:
"Bingo!"[0]

'B'

In [77]:
"Bingo!"[-len("Bingo!")]

'B'

In [79]:
first, *_ = "Bingo!"
first

'B'

Extract the letter "u" from "Constitution".

In [80]:
# search for letter "u"
"Constitution".index("u")

7

In [81]:
"Constitution"[7]

'u'

In [83]:
"Constitution"[7-len("Constitution")]

'u'

________________

# Structure Your Code with Indentation

Use indentation properly to print the result of the function with an argument of 3.

In [84]:
# Parameters and Arguments
# Within function itself which value comes from argument it doesnt matter it will assign 10 to x and will return back 10
def ten(x):
    x = 10
    return x
print (ten(3))

10


___________________

# Comparison Operators

Verify that 25 is smaller than 30.

In [85]:
25 < 30

True

Verify that 5 multiplied by 3 is less than or equal to 5 to the power of 3.

In [86]:
5 * 3 <= 5 ** 3

True

Verify that 100 is equal to 10 square.

In [87]:
100 == 10 ** 2

True

Verify that 53 is not equal to 46.

In [88]:
53 != 46

True

___________________

# Logical and Identity Operators 

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Check whether the following code is True or False.

False or not True and not False

In [89]:
# The order of logical operators start from not, then true and then false. In case of parathesis gives firstly perform inside paranthesis.
# 1. False or False and True
# 2. False or False
# 3. False
False or not True and not False

False

True and not False and True or not False

In [90]:
# 1. True and True and True or True
# 2. True and True or True
# 3. True or True
# 4. True
True and not False and True or not False

True

True or False and False

In [92]:
# True or False
# True
True or False and False

True

False and True or False

In [93]:
# False or False
# False
False and True or False

False

Using an identity operator, verify that 10 is not the same as 12.

In [95]:
10 != 12

True

Using an identity operator, verify that 50 is the same as 50.

In [96]:
50 == 50

True

____________________

# Introduction to the IF statement

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Create a two-line code that prints "The condition has been satisfied" if 5 is greater than 2.

In [97]:
if 5 > 2:
    print("The condition has been satisfied")

The condition has been satisfied


Assign 10 to the variable x and 25 to the variable y. In the same cell, create 2 conditional statements. Let the first one print "Both conditions are correct" if x is greater then 3 and y is greater than 13. Let the second one print "At least one of the conditions is false" if x is less than or equal to 3 and y is less than or equal to 13. Change the values assigned to x and y and re-run the cell to verify your code still works.

In [103]:
x = 10
y = 5
if x > 3 and y > 13:
    print("Both conditions are true")
elif x <= 3 and y <= 13:
    print("Both conditions are false")
else:
    print("At least one of the conditions is false")

At least one of the conditions is false


____________________________

# Add an ELSE Statement

Let x represent the number of orders received during a certain day. Assign 102 to x. Create a program that prints "A busy day" if x is greater than 100, and "A calm day" otherwise. Change x to 97 to verify your code works properly.

In [105]:
x = 97
if x > 100:
    print("A busy day")
else:
    print("A calm day")

A calm day


_________________

# Else if, for Brief - ELIF

Assign 200 to x. Create the following piece of code: If x > 200, print out "Big"; If x > 100 and x <= 200, print out "Average"; and If x <= 100, print out "Small". Use the If, Elif, and Else keywords in your code.

In [118]:
# Assign initial value to variable
x = 200
# Creating function because calling in the second line again because otherwise I should copy and paste same if statement again
def number_type(x):
    # Creating if statement
    if x > 200:
        print("Big")
    elif 100 < x <= 200:
        print("Average")
    elif 0 <= x <= 100:
        print("Small")
    else:
        print("Negative")

number_type(x)

Average


Change the initial value of x to see how your output will vary.

In [119]:
x = 300
number_type(x)

Big


Keep the first two conditions of the previous code. Add a new ELIF statement, so that, eventually, the program prints "Small" if x >= 0 and x <= 100, and "Negative" if x < 0. Let x carry the value of 50 and then of -50 to check if your code is correct.

In [124]:
x = 50
number_type(x)
x = -50
number_type(x)

Small
Negative


_____________________

# Creating a Function with a Parameter

Define a function that returns a value equal to its argument multiplied by 2.

In [131]:
def multiplier(x: float):
    """
    Description:
        This function take argument from user then multiply by 2 and return final value 
    Args:
        x (float): The value which will be multiplied by 2
    Return:
        x * 2
    """
    return x * 2

In [132]:
help(multiplier)

Help on function multiplier in module __main__:

multiplier(x: float)
    Description:
        This function take argument from user then multiply by 2 and return final value
    Args:
        x (float): The value which will be multiplied by 2
    Return:
        x * 2



In [133]:
multiplier(7)

14

Define a funciton that returns a float value equal to its argument divided by 2.

In [134]:
def divider(x: float):
    """
    Description:
        This function take argument from user then divide by 2 and return final value 
    Args:
        x (float): The value which will be divided by 2
    Return:
        x / 2
    """
    return x / 2

In [135]:
help(divider)

Help on function divider in module __main__:

divider(x: float)
    Description:
        This function take argument from user then divide by 2 and return final value
    Args:
        x (float): The value which will be divided by 2
    Return:
        x / 2



In [136]:
divider(24.6)

12.3

_________________

# Another Way to Define a Function

Define a function that states the value of the argument accompanied by the phrase "Raised to the power of 2:" and returns a value equal to its argument raised to the power of 2. This time, use a new variable, called "result", in the body of the Function. Call the function with some argument to verify it works properly.

Hint: Your knowledge about stating multiple elements on a line can be of great help in solving this exercise!

In [146]:
def power(x: float):
    """
    Description:
        This function take argument from user then raised it to the power of 2
        Then return in this format: x raised to the power of 2: x**2
    Args:
        x (float): The value which will be raised to the power of 2
    Return:
        result (str): x raised to the power of 2: x**2
    """
    result = f"{x} raised to the power of 2: {x**2}"
    return result

In [147]:
help(power)

Help on function power in module __main__:

power(x: float)
    Description:
        This function take argument from user then raised it to the power of 2
        Then return in this format: x raised to the power of 2: x**2
    Args:
        x (float): The value which will be raised to the power of 2
    Return:
        result (str): x raised to the power of 2: x**2



In [138]:
power(5)

'5 raised to the power of 2: 25'

_____________

# Using a Function in Another Function

Define a function that adds 5 to the parameter. Then, define another function that will multiply the newly obtained number by 3. Verify your code was correct by calling the second function with an argument of 5. Was your output equal to 30?

In [142]:
# Method 1: Independent functions
def adder(x: float):
    return x + 5
    
def multiplier(x: float):
    return x*3

multiplier(adder(5))

30

In [145]:
# Method 2: Nested functions
def multiplier(x: float):
    
    def adder(x: float):
        return x + 5
        
    return adder(x) * 3

multiplier(5)

30

____________________

# Combining Conditional Statements and Functions

Define a function, called compare_the_two(), with two arguments. If the first one is greater than the second one, let it print "Greater". If the second one is greater, it should print "Less". Let it print "Equal" if the two values are the same number.

In [149]:
def compare_the_two(first, second):
    if first > second:
        return "Greater"
    elif first < second:
        return "Less"
    else:
        return "Equal"

In [152]:
print(compare_the_two(5, 6))
print(compare_the_two(13, 7))
print(compare_the_two(4, 4))

Less
Greater
Equal


__________________

# Notable Built-In Functions in Python

Obtain the maximum number among the values 25, 65, 890, and 15.

In [153]:
data = [25, 65, 890, 15]
max(data)

890

Obtain the minimum number among the values 25, 65, 890, and 15.

In [154]:
min(data)

15

Find the absolute value of -100

In [155]:
abs(-100)

100

Round the value of 55.5. Did you obtain 56.0?

In [156]:
# In the round function it will be round two nearest even number if in the middle of two integers
round(55.5)

56

Round 35.56789 to the third digit.

In [157]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.

    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [158]:
round(35.56789, 3)

35.568

Find the sum of all elements in the provided list, called "Numbers".

In [160]:
Numbers = [1, 5, 64, 24.5]

In [161]:
sum(Numbers)

94.5

Use a built-in function to raise 10 to the power of 3.

In [162]:
help(pow)

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments

    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [163]:
pow(10, 3)

1000

How many characters are there in the word "Elephant"?

In [165]:
len("Elephant")

8

Create a function, called "distance_from_zero", that returns the absolute value of a provided single argument and prints a statement "Not Possible" if the argument provided is not a number. Call the funtion with the values of -10 and "cat" to verify it works correctly.

In [182]:
def distance_from_zero(x: float):
    """
    Desc:
        This function will calculate the distance of argument from 0 which added by user
    Args:
        x (float): Take user defined argument in order to calculate distance from 0
    Return:
        In case of non-numeric input it will return "Not Possible" string
        In case argument is numeric function performs abs() function in order to find absolute form of numeric argument
    """
    if isinstance(x, float) or isinstance(x, int):
        return abs(x)
    else:
        return "Not Possible"

In [183]:
help(distance_from_zero)

Help on function distance_from_zero in module __main__:

distance_from_zero(x: float)
    Desc:
        This function will calculate the distance of argument from 0 which added by user
    Args:
        x (float): Take user defined argument in order to calculate distance from 0
    Return:
        In case of non-numeric input it will return "Not Possible" string
        In case argument is numeric function performs abs() function in order to find absolute form of numeric argument



In [181]:
distance_from_zero(-10)

10

In [180]:
distance_from_zero("cat")

'Not Possible'

____________________

# Lists

Create a list, called "Numbers". Let it contain the numbers 10, 25, 40, and 50.

In [184]:
Numbers = [10, 25, 40, 50]
Numbers

[10, 25, 40, 50]

Print the second element from the list.

In [186]:
Numbers[1]

25

Print the 0th element.

In [187]:
print(Numbers[0])

10


Print the third-to-last element using a minus sign in the brackets.

In [189]:
print(Numbers[-3])

25


Substitute the number 10 with the number 15.

In [190]:
Numbers[0] = 15
Numbers

[15, 25, 40, 50]

Delete the number 25 from the Numbers list.

In [192]:
Numbers.remove(25)
Numbers

[15, 40, 50]

______________

# Help Yourself with Methods

Append the number 100 to the Numbers list.

In [200]:
Numbers = [15, 40, 50]

In [201]:
Numbers.append(100)
Numbers

[15, 40, 50, 100]

With the help of the "extend method", add the numbers 115 an 140 to the list.

In [202]:
new_numbers = [115, 140]
Numbers.extend(new_numbers)
Numbers

[15, 40, 50, 100, 115, 140]

Print a statement, saying "The fourth element of the Numbers list is:" and then designate the value of the fourth element. Use a trailing comma.

In [203]:
print("The fourth element of the Numbers list is:", Numbers[4])

The fourth element of the Numbers list is: 115


How many elements are there in the Numbers list?

In [204]:
len(Numbers)

6

________________

# List Slicing

In [ ]:
Numbers = [15, 40, 50, 100, 115, 140]

Using list slicing, obtain the numbers 100 and 115.

In [208]:
# finding index of numbers
start_index = Numbers.index(100)
end_index = Numbers.index(115) + 1
Numbers[start_index : end_index]

[100, 115]

Using slicing, extract the first four elements from the list.

In [209]:
Numbers[0:4]

[15, 40, 50, 100]

Using slicing, extract all the elements from the list from the 3rd position onwards.

In [210]:
# From the 3rd position onwards: 3rd element stay in index 2 and onwards will be till the end of list
Numbers[2:]

[50, 100, 115, 140]

Using slicing, extract the last 4 elements from the list.

In [211]:
# Last for elements starts from -4, -3, -2, -1 index positions
Numbers[-4:]

[50, 100, 115, 140]

Which is the position of the value 15?

In [212]:
Numbers.index(15)

0

Create a list, called "Two_Numbers". Let its elements be the values 1 and 2. Then, create a new one, named "All_Numbers", that will containt both the "Numbers" and the "Two_Numbers" lists.

In [218]:
Two_Numbers = [1, 2]
# Method 1 - Concatinating
All_Numbers = Two_Numbers + Numbers
print("Method 1:", All_Numbers)
# Method 2 - Together but splitting
All_Numbers = [Two_Numbers, Numbers]
print("Method 2:", All_Numbers)
# Method 3 - Extending one them with another one and copy with reference method
# NOTE: In this method we also change the extending list
Two_Numbers.extend(Numbers)
All_Numbers = Two_Numbers
print("Method 3:", All_Numbers)

Method 1: [1, 2, 15, 40, 50, 100, 115, 140]
Method 2: [[1, 2], [15, 40, 50, 100, 115, 140]]
Method 3: [1, 2, 15, 40, 50, 100, 115, 140]


Sort all the numbers in the "Numbers" list from the largest to the smallest.

In [222]:
# Method 1 - .sort() method of list class
Numbers.sort(reverse=True)
print("Method 1:", Numbers)
# Method 2 - sorted() built-in function
sorted_numbers_desc = list(sorted(Numbers, reverse=True))
print("Method 2:", sorted_numbers_desc)

Method 1: [140, 115, 100, 50, 40, 15]
Method 2: [140, 115, 100, 50, 40, 15]


_____________________________________________________________________________________________________________

# Tuples

Create a tuple, called "Cars", with elements "BMW", "Dodge", and "Ford".

In [224]:
Cars = ("BMW", "Dodge", "Ford")
type(Cars)

tuple

Access the second element of this tuple.

In [225]:
Cars[1]

'Dodge'

Call a method that would allow you to extract the provided name and age separately. Then print the "name" and "age" values to see if you worked correctly.

In [229]:
name, age = 'Peter,24'.split(",")

In [230]:
print(f"name: {name}\nage: {age}")

name: Peter
age: 24


Create a function that takes as arguments the two values of a rectangle and then returns the Area and the Perimeter of the rectangle. Call the function with arguments 2 and 10 to verify it worked correctly.

In [236]:
def rectangle(height, width):
    area = height * width
    perimeter = (height + width) * 2
    return f"Area: {area}\nPerimeter: {perimeter}"
print(rectangle(2, 10))

Area: 20
Perimeter: 24


________________________

# Dictionaries

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

This is the menu of a close-by restaurant:

In [248]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'}

What is the second meal in the list?

In [249]:
Menu.get("meal_2")

'Fries'

Add a new meal - "Soup".

In [250]:
# Method 1 - with key assign value
Menu["meal_5"] = "Soup"
print("-----Method 1-----\n", Menu)
# Method 2 - .update() method
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'} # Reset 
Menu.update({"meal_5" : "Soup"})
print("-----Method 2-----\n", Menu)

-----Method 1-----
 {'meal_1': 'Spaghetti', 'meal_2': 'Fries', 'meal_3': 'Hamburger', 'meal_4': 'Lasagna', 'meal_5': 'Soup'}
-----Method 2-----
 {'meal_1': 'Spaghetti', 'meal_2': 'Fries', 'meal_3': 'Hamburger', 'meal_4': 'Lasagna', 'meal_5': 'Soup'}


Replace the Hamburger with a Cheeseburger.

In [251]:
Menu["meal_3"] = "Cheesburger"
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheesburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup'}

Attach the Desserts list in the form of a sixth meal.

In [252]:
Dessert = ['Pancakes', 'Ice-cream', 'Tiramisu']

In [253]:
Menu.update({"meal_6":Dessert})
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheesburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup',
 'meal_6': ['Pancakes', 'Ice-cream', 'Tiramisu']}

Create a new dictionary that contains the first five meals as keys and assign the following five values as prices (in dollars): 10, 5, 8, 12, 5. Start by Price_list = {}.

In [268]:
# Create Price_list empty dictionary
Price_list = dict()
# Create list where prices stay
prices = [10, 5, 8, 12, 5]
# Counter for looping through prices list
index = 0
# Taking keys from Menu dictionary we can perform it with Menu.values() method without preserving keys
for key, value in Menu.items():
    # if condition for checking first 5 items from Menu list. Because after updating with desert it have 6 items inside
    if index == 5:
        break
    # Assigning values from Menu as keys in Price_list
    Price_list[value] = f"${prices[index]}"
    index += 1
Price_list

{'Spaghetti': '$10',
 'Fries': '$5',
 'Cheesburger': '$8',
 'Lasagna': '$12',
 'Soup': '$5'}

Use the .get() method to check the price of the Spaghetti.

In [269]:
Price_list.get("Spaghetti")

'$10'

_____________________

# For Loops

Create a For loop that prints every digit on a new line.

In [271]:
digits = [0,1,2,3,4,5,6,7,8,9]

In [272]:
for d in digits:
    print(d)

0
1
2
3
4
5
6
7
8
9


Adjust the code, so the digits are all printed on the same line.

In [273]:
for d in digits:
    print(d, end=" ")

0 1 2 3 4 5 6 7 8 9 

________________

# While Loops and Incrementing

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Create a while loop that will print all odd numbers from 0 to 30 on the same row.

Hint: There are two ways in which you can create the odd values!

In [275]:
i = 0
while i <= 30:
    if i % 2 == 1:
        print(i, end=" ")
    i += 1

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 

In [276]:
i = 1
while i <= 30:
    print(i, end=" ")
    i += 2

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 

____________

# Create Lists with the range() Function

Use the range() function to create a list with all numbers from 1 to 10.

In [279]:
data = list(range(1, 11))
data

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Use the range() function to create a list with all numbers from 0 to 19.

In [280]:
data = list(range(0, 20))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

Use the range function to create a list with all even numbers from 0 to 30 included.

In [281]:
data = list(range(0, 31, 2))
data

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

_______________________

# Use Conditional Statements and Loops Together

Create a For loop that will print all the variables from a given list multiplied by 2. Let the list contain all numbers from 1 to 10. Create it with the help of the range() function.

In [283]:
for d in range(1, 11):
    print(d*2, end=" ")

2 4 6 8 10 12 14 16 18 20 

Create a little program that runs a loop over all values from 1 to 30. Let it print all Odd numbers, and in the place of the even numbers, it should print "Even". Help yourself with the range() function to solve this exercise.

In [284]:
def print_odds():
    for i in range(1, 31):
        if i % 2 == 1:
            print(i, end=" ")
        else:
            print("Even", end=" ")
print_odds()

1 Even 3 Even 5 Even 7 Even 9 Even 11 Even 13 Even 15 Even 17 Even 19 Even 21 Even 23 Even 25 Even 27 Even 29 Even 

You have the following list of numbers. Iterate over this list, printing out each list value multiplied by 10. Find two solutions of this problem.

In [285]:
n = [1,2,3,4,5,6]

In [290]:
# Method 1
for i in range(0, len(n)):
    print(n[i] * 10, end=" ")

10 20 30 40 50 60 

In [291]:
# Method 2
for i in n:
    print(i * 10, end=" ")

10 20 30 40 50 60 

_________________

# All in - Conditional Statements, Functions, and Loops

You are provided with the 'nums' list. Complete the code in the cell that follows. Use a while loop to count the number of values lower than 20. You might prefer using the x[item] structure for indicating the value of an element from the list.

In [293]:
nums = [1,12,24,31,51,70,100]

In [302]:
i = 0
counter = 0
nums_less_than_20 = []
while nums[i] < 20:
    nums_less_than_20.append(nums[i])
    counter += 1
    i += 1
print(f"Data: {nums}\nSelections: {nums_less_than_20}\nCount: {counter}")

Data: [1, 12, 24, 31, 51, 70, 100]
Selections: [1, 12]
Count: 2


____________

# Iterating over Dictionaries

In this exercise you will use the same dictionaries as the ones we used in the lesson - "prices" and "quantity". This time, don't just calculate all the money Jan spent. Calculate how much she spent on products with a price of 5 dollars or more.

In [314]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [315]:
# 5 dollars or more products
expensive_products = []
expensive_spent = 0

for key in prices.keys():
    money_spent += prices[key] * quantity[key]
    if prices[key] >= 5:
        expensive_products.append(key)
        expensive_spent += prices[key] * quantity[key]
        
print(f"Total Spent: {money_spent}\nExpensive Products: {expensive_products}\nSpent on Expensives: {expensive_spent}")

Total Spent: 74
Expensive Products: ['lasagna']
Spent on Expensives: 50


And how much did Jan spent on products that cost less than 5 dollars?

In [317]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [318]:
# Products which cost less than 5 dollars
cheap_products = []
cheap_spent = 0

for key in prices.keys():
    if prices[key] < 5:
        cheap_products.append(key)
        cheap_spent += prices[key] * quantity[key]
        
print(f"Cheap Products: {cheap_products}\nSpent on Cheaps: {cheap_spent}")

Cheap Products: ['box_of_spaghetti', 'hamburger']
Spent on Cheaps: 24
